
image_topic: "/cam0/image_raw"
camera_cfg:
   model_type: PINHOLE
   camera_name: camera
   image_width: 752
   image_height: 480
   distortion_parameters:
      k1: -2.917e-01
      k2: 8.228e-02
      p1: 5.333e-05
      p2: -1.578e-04
   projection_parameters:
      fx: 4.616e+02
      fy: 4.603e+02
      cx: 3.630e+02
      cy: 2.481e+02
point_feature_cfg:
        weights_path: '/home/plus/Work/plvins_ws/src/PL-VINS/feature_tracker/scripts/superpoint/superpoint_v1.pth'
        max_length: 5  # Maximum length of point tracks
        nms_dist: 4    # Non Maximum Suppression (NMS) distance
        conf_thresh: 0.015 # Detector confidence threshold
        nn_thresh: 0.7 # Descriptor matching threshold 
        cuda: false # Use cuda GPU to speed up network processing speed
        H: 480 # Input image height
        W: 752 # Input image width
        min_cnt: 150
line_feature_cfg:
        cross_check: True
        num_samples: 5
        min_dist_pts: 8
        top_k_candidates: 10
        grid_size: 4
        line_score: false
        sampling: "regular"
        H: 480 # Input image height
        W: 752 # Input image width
        min_cnt: 60